### ISSUE TITLE
Supports `CONNECT` request?

### ISSUE THREAD

**Issue by DUOLabs333** [ChandraNarreddy/sniproxy#31]
AKA, can this act as a reverse proxy for my mitmproxy instance? So, when I call `curl -x sniproxy.test google.com`, it passes the `CONNECT` request to the proxy behind it?

**Comment by ChandraNarreddy** [comment]
Hi, sorry about the delay in my response. I have not tested CONNECT method specifically, but there is no reason it should not be able to proxy CONNECT requests. But please do note that it does not support tunnelling TCP connections directly using CONNECT requests to a non-HTTP server.
